import pandas as pd
from src.utils import money,mask

def report(df,inventory,path):
    dt=pd.to_datetime(df.tanggal_transaksi,format='%d/%m/%y',errors='coerce'); outgoing=df[df.debet.fillna(0)>0]; suspicious=df[df.risk_level.isin(['HIGH','CRITICAL'])];review=df[df.review_required]; mismatch=df[df.reconciliation_status=='MISMATCH']
    lines=['# Analisis Rekening BRI','','**Dokumen penyaringan awal, bukan penetapan tindak pidana.** Angka OCR yang belum dapat divalidasi tidak boleh dianggap pasti.','', '## 1. Ringkasan Eksekutif',f'- Periode terbaca: {dt.min()} sampai {dt.max()}',f'- Jumlah baris OCR transaksi: {len(df)}',f'- Debit terbaca: {money(df.debet.sum())}',f'- Kredit terbaca: {money(df.kredit.sum())}',f'- Saldo awal/akhir pada baris yang diekstrak (bukan saldo periode): {money(df.saldo.iloc[0] if len(df) else None)} / {money(df.saldo.iloc[-1] if len(df) else None)}','','## 2. Kemana Uang Keluar']
    dest=outgoing.groupby('destination_normalized').agg(total=('debet','sum'),count=('debet','size')).sort_values('total',ascending=False)
    for i,(name,row) in enumerate(dest.head(10).iterrows(),1):lines.append(f'{i}. {mask(name)} — {money(row.total)} — {int(row["count"])} transaksi')
    from src.statement_totals import TOTALS
    printed_debit=sum(v['total_debit'] for v in TOTALS.values()); printed_credit=sum(v['total_credit'] for v in TOTALS.values())
    lines+=['','### Pemeriksaan terhadap total tercetak pada rekening koran',f'- Total debit tercetak (Juli–September): {money(printed_debit)}; total baris debit OCR terbaca: {money(df.debet.sum())}; **selisih belum teralokasi: {money(printed_debit-df.debet.sum())}**.',f'- Total kredit tercetak: {money(printed_credit)}; OCR terbaca: {money(df.kredit.sum())}.']
    for month,tot in TOTALS.items():
        m=dt.dt.strftime('%Y-%m')==month; lines.append(f"- {month}: debit tercetak {money(tot['total_debit'])}, OCR {money(df.loc[m,'debet'].sum())}, selisih {money(tot['total_debit']-df.loc[m,'debet'].sum())}; kredit tercetak/OCR {money(tot['total_credit'])}/{money(df.loc[m,'kredit'].sum())}.")
    lines+=['- Total bulanan tercetak hanya acuan pengendalian, bukan pengganti nominal transaksi yang OCR-nya belum pasti.','', '**UNKNOWN berarti uraian tidak memuat penerima yang dapat dipastikan; kode internal bank bukan nama tujuan.**','','## 3. Jenis Transaksi']
    for name,row in outgoing.groupby('transaction_category').agg(total=('debet','sum'),count=('debet','size')).sort_values('total',ascending=False).iterrows():lines.append(f'- {name}: {money(row.total)} ({int(row["count"])} transaksi)')
    lines+=['','## 4. Transaksi Terbesar']
    for _,r in outgoing.nlargest(10,'debet').iterrows():lines.append(f'- {r.tanggal_transaksi}: {money(r.debet)} — {mask(r.destination_normalized)}, sumber {r.source_page}')
    lines+=['','## 5. Transaksi Mencurigakan']
    for _,r in suspicious.iterrows():lines.append(f'- {r.tanggal_transaksi} — {money(r.debet)} — {mask(r.destination_normalized)} — {r.transaction_category} / {r.channel} — **{r.risk_level}**: {r.risk_reason}')
    if suspicious.empty:lines.append('Tidak ada baris HIGH/CRITICAL dari aturan penyaringan yang diterapkan.')
    lines+=['','**Perhatian:** Skor risiko adalah penyaring kasar, bukan bukti penipuan. Periksa manual transaksi besar, transaksi berurutan, serta anotasi/highlighting yang tampak pada gambar.','', '## 6. Pola Transaksi Mencurigakan']
    for key,g in suspicious.groupby('transaction_cluster_id'):lines.append(f'- {key}: {len(g)} transaksi flagged, debit {money(g.debet.sum())}; tanggal {g.tanggal_transaksi.min()}–{g.tanggal_transaksi.max()}')
    lines+=['','## 7. Counterparty Baru','- Data uraian umumnya memakai kode internal. Identitas penerima baru **tidak dapat dipastikan** tanpa data transfer rinci BRI.','','## 8. Perubahan Pola Rekening',f'- Median debit yang terbaca: {money(outgoing.debet.median() if len(outgoing) else None)}. Sejarah hanya periode dokumen ini; baseline sebelum insiden tidak diketahui.','','## 9. Rekonsiliasi Saldo',f'- MATCH: {(df.reconciliation_status=="MATCH").sum()}; MISMATCH: {len(mismatch)}; CANNOT_VALIDATE: {(df.reconciliation_status=="CANNOT_VALIDATE").sum()}.','- Ketidakcocokan bisa disebabkan kesalahan OCR, halaman hilang atau urutan salah; tidak diperbaiki tanpa bukti.','','## 10. Data yang Perlu Diverifikasi Manual',f'- {len(review)} baris OCR memerlukan pemeriksaan; {len(mismatch)} selisih saldo. Lihat tab OCR Review dan Reconciliation dalam workbook.','- Periksa juga semua angka sumber pada gambar, terutama debit nominal besar dan saldo yang tercetak samar.','','## 11. Kesimpulan Investigasi',f'- Total outgoing yang **berpotensi** memerlukan investigasi (HIGH/CRITICAL, menurut data terbaca): {money(suspicious.debet.sum())}.','- Tujuan UNKNOWN tidak boleh diartikan sebagai satu penerima. Mintalah detail referensi transfer, rekening tujuan, dan bukti mutasi dari BRI.','- Temuan ini merupakan indikator untuk diverifikasi lebih lanjut dengan BRI dan pihak berwenang; bukan kesimpulan hukum.','','## Keterbatasan Sumber',f'- {len(inventory)} gambar diproses; kemungkinan rincian penerima tidak tercetak dalam uraian. Nilai tidak terbaca dibiarkan kosong, bukan nol.']
    from pathlib import Path
    Path(path).write_text('\n'.join(lines)+'\n',encoding='utf-8')
